### ISSUE TITLE
[Bug]: Enabling this plugin changes some text color in obsidian ui

### ISSUE THREAD

**Issue by meskill** [dpickett/open-related-url#4]
Something strange happens when I enable this plugin in my vault.

After enabling text in settings tab and inside an editor becomes red as you can see in gif below
![ObsidianRelatedPluginBug](https://user-images.githubusercontent.com/8974488/183060716-687ddaa7-fed5-48af-b98f-2efb402abe51.gif)

I've tried to reload Obsidian but red text is still there when this plugin is enabled - after disabling it becomes default again

Any idea why this happens and how to fix it?

**Comment by MMS-PCLN** [comment]
I've the same problem: Obsidian v0.15.9 on MacOS 12.5.

**Comment by dpickett** [comment]
hey there, this is a confirmed bug - in development, I thought / assumed it was due to me manually installing it thus signaling that the plugin was unsafe. But, after installing the version officially through community plugins, I'm seeing the same behavior.

I've asked other devs in the discord channel to see if anyone has seen this before. I did do some checking around prior to launching this but came up dry.

**Comment by dpickett** [comment]
my bad with some help from an awesome discord user I discovered there's some boilerplate code in our `styles.css` - I'll get this patched up. 

filed an issue with the boilerplate as that seems like a weird default. https://github.com/obsidianmd/obsidian-sample-plugin/issues/35
